replicaCount: 1
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
  basedomain: opspresso.com
hpa:
  enabled: true
  min: 2
  max: 30
  cpu: 50
env:
envFrom:
configmap:
  enabled: false
  data:
    PROFILE: development
secret:
  enabled: false
  data:
    PASSWORD: cGFzc3dvcmQ=
