#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: opspresso/awscli
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            ./package.sh
            ./publish.sh toast.sh
            ./publish.sh repo.toast.sh
            ./publish.sh www.toast.sh
      - store_artifacts:
          path: ~/repo/target
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target/*
  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: target
      - run:
          name: "Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(cat target/toaster.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} target/dist/

workflows:
  version: 2
  maven:
    jobs:
      - build
      - release:
          requires:
            - build
