#
# CircleCI 2.0
#
version: 2
jobs:
  package:
    docker:
      - image: circleci/python
    working_directory: /tmp/works
    steps:
      - checkout
      - run:
          name: Package
          command: |
            chmod 755 ./build.sh
            ./build.sh package
      - persist_to_workspace:
          root: /tmp/works
          paths:
            - target/*
            - build.sh
  publish:
    docker:
      - image: opspresso/awscli
    steps:
      - attach_workspace:
          at: works
      - run:
          name: Publish
          command: |
            chmod 755 ./works/build.sh
            ./works/build.sh publish
  prerelease:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: works
      - run:
          name: Release
          command: |
            chmod 755 ./works/build.sh
            ./works/build.sh prerelease
  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: works
      - run:
          name: Release
          command: |
            chmod 755 ./works/build.sh
            ./works/build.sh release
  slack:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: works
      - run:
          name: Slack
          command: |
            chmod 755 ./works/build.sh
            ./works/build.sh slack

workflows:
  version: 2
  apply:
    jobs:
      - package
      - approval:
          type: approval
          requires:
            - package
      - publish:
          requires:
            - approval
      - release:
          requires:
            - approval
      - slack:
          requires:
            - release
