#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - checkout
      - run:
          name: Package
          command: |
            mkdir target
            curl -sLo target/builder.sh toast.sh/builder
            bash ./target/builder.sh
      - persist_to_workspace:
          root: ~/works
          paths:
            - target
  package:
    docker:
      - image: opspresso/awscli
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Package
          command: |
            bash ./package.sh
  publish:
    docker:
      - image: opspresso/awscli
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Publish
          command: |
            bash ./target/builder.sh
  release:
    docker:
      - image: circleci/golang
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Release
          command: |
            bash ./target/builder.sh
  slack:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Slack
          command: |
            bash ./target/builder.sh

# Advanced Settings
# - Build forked pull requests
# - Pass secrets to builds from forked pull requests
# - Only build pull requests

workflows:
  version: 2
  apply:
    jobs:
      - build
      - package:
          requires:
            - build
      - publish:
          requires:
            - package
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - package
      - slack:
          requires:
            - release
