#
# CircleCI 2.0
#
version: 2
jobs:
  package:
    docker:
      - image: circleci/python
    working_directory: /tmp/works
    steps:
      - checkout
      - run:
          name: Package
          command: |
            bash ./builder.sh package
            bash ./build.sh
      - persist_to_workspace:
          root: /tmp/works
          paths:
            - target/*
            - builder.sh
  publish:
    docker:
      - image: opspresso/awscli
    steps:
      - attach_workspace:
          at: works
      - run:
          name: Publish
          command: |
            bash ./works/builder.sh publish ./works
  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: works
      - run:
          name: Release
          command: |
            bash ./works/builder.sh release ./works
  slack:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: works
      - run:
          name: Slack
          command: |
            bash ./works/builder.sh slack ./works

workflows:
  version: 2
  apply:
    jobs:
      - package
      - publish:
          requires:
            - package
      - release:
          requires:
            - package
      - slack:
          requires:
            - release
