#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: opspresso/awscli
    steps:
      - checkout
      - run: ./package.sh
      - run: ./publish.sh toast.sh
      - run: ./publish.sh repo.toast.sh
      - run: ./publish.sh www.toast.sh
