#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: opspresso/awscli
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            ./package.sh
            ./publish.sh toast.sh
            ./publish.sh repo.toast.sh
            ./publish.sh www.toast.sh
  release:
    docker:
      - image: circleci/golang
    steps:
      - run:
          name: "Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(cat VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} target/dist/

workflows:
  version: 2
  maven:
    jobs:
      - build
      - release:
          requires:
            - build
