#
# CircleCI 2.0
#
version: 2
jobs:
  package:
    docker:
      - image: circleci/python
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Package
          command: |
            chmod 755 ./build.sh
            ./build.sh package
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/*
            - build.sh
  publish:
    docker:
      - image: opspresso/awscli
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Publish
          command: |
            chmod 755 ./workspace/build.sh
            ./workspace/build.sh publish
  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Release
          command: |
            chmod 755 ./workspace/build.sh
            ./workspace/build.sh release
  slack:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Slack
          command: |
            chmod 755 ./workspace/build.sh
            ./workspace/build.sh slack

workflows:
  version: 2
  apply:
    jobs:
      - package
      - publish:
          requires:
            - package
      - release:
          requires:
            - package
      - slack:
          requires:
            - release
