#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Build
          command: |
            bash ./build.sh
  package:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - checkout
      - run:
          name: Package
          command: |
            mkdir target
            curl -sLo target/builder.sh toast.sh/builder
            bash ./target/builder.sh package
      - persist_to_workspace:
          root: ~/works
          paths:
            - target
  publish:
    docker:
      - image: opspresso/awscli
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Publish
          command: |
            bash ./target/builder.sh publish
  release:
    docker:
      - image: circleci/golang
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Release
          command: |
            bash ./target/builder.sh release
  slack:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Slack
          command: |
            bash ./target/builder.sh slack

workflows:
  version: 2
  apply:
    jobs:
      - package
      - publish:
          requires:
            - package
      - release:
          requires:
            - package
      - slack:
          requires:
            - release
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
