name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
