name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Prepare
      run: |
        mkdir target
        # curl -sLo target/actions toast.sh/actions
        cp actions.sh target/actions

    - name: Build
      env:
        STRING: ${{ STRING }}
      run: |
        bash ./target/actions build

    - name: Package
      run: |
        bash ./package.sh

    - name: Publish
      env:
        PUBLISH_PATH: ${{ secrets.PUBLISH_PATH }}
      run: |
        bash ./target/actions publish

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash ./target/actions release

    - name: Slack
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        bash ./target/actions slack
