name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Prepare
      run: |
        mkdir target
        # curl -sLo target/actions toast.sh/actions
        cp actions.sh target/actions

    - name: Build
      run: |
        bash ./target/actions build

    - name: Package
      run: |
        bash ./package.sh

    - name: Publish
      run: |
        bash ./target/actions publish

    - name: Release
      run: |
        bash ./target/actions release

    - name: Slack
      run: |
        bash ./target/actions slack
