name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Prepare
      run: |
        mkdir target
        # curl -sLo target/actions toast.sh/actions
        cp actions.sh target/actions

    - name: Build
      env:
        STRING: ${{ secrets.STRING }}
      run: |
        bash ./target/actions build

    - name: Package
      run: |
        bash ./package.sh

    - name: Publish
      uses: opspresso/action-s3-sync@v0.0.2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: "www.toast.sh"
        AWS_REGION: "ap-northeast-2"
        DEST_PATH: "/temp"
        FROM_PATH: "./target/publish"

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash ./target/actions release

    - name: Slack
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        bash ./target/actions slack
