name: Build-PR

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Prepare
      run: |
        mkdir target
        # curl -sLo target/actions toast.sh/actions
        cp actions.sh target/actions

    - name: Build
      run: |
        bash ./target/actions build

    - name: Package
      run: |
        bash ./package.sh

    # - name: Release
    #   uses: opspresso/action-release@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PRERELEASE: "true"
    #     ASSET_PATH: ./target/release

    - name: Slack
      uses: opspresso/action-slack@master
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        JSON_PATH: ./target/slack_message.json
