name: Build-Push

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Prepare
      run: |
        mkdir target
        # curl -sLo target/actions toast.sh/actions
        cp actions.sh target/actions

    - name: Build
      env:
        STRING: ${{ secrets.STRING }}
      run: |
        bash ./target/actions build

    - name: Package
      run: |
        bash ./package.sh

    - name: Publish
      uses: opspresso/action-s3-sync@master
      with:
        args: --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-northeast-2"
        FROM_PATH: "./target/publish"
        DEST_PATH: ${{ secrets.PUBLISH_DEST_PATH }}

    - name: Release
      uses: opspresso/action-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: "$(cat ./target/VERSION | xargs)"

    - name: Slack
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        bash ./target/actions slack
