name: Build-Push

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      run: |
        mkdir target
        # curl -sLo target/actions toast.sh/actions
        cp actions.sh target/actions
        bash ./target/actions build

    - name: Package
      run: |
        bash ./package.sh

    - name: Publish
      uses: opspresso/action-builder@master
      with:
        args: --cmd publish
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-northeast-2"
        FROM_PATH: "./target/publish"
        DEST_PATH: ${{ secrets.PUBLISH_DEST_PATH }}
        OPTIONS: "--acl public-read"

    - name: Release
      uses: opspresso/action-builder@master
      with:
        args: --cmd release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASSET_PATH: ./target/release

    - name: Slack
      uses: opspresso/action-builder@master
      with:
        args: --cmd slack
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        JSON_PATH: ./target/slack_message.json
